<a href="https://colab.research.google.com/github/Khulbe-Nitin/Volt-Relay/blob/main/Collab_notebook/abhishek_fourdataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [90]:
import pandas as pd
import numpy as np

In [91]:
from google.colab import files
files.upload()

Saving batteries.csv to batteries (1).csv

{'batteries (1).csv': b'battery_id,pack_type,supplier,manufacturing_lot,manufacture_date,commission_date,rated_capacity_kwh,purchase_cost_inr,initial_soh_pct,bms_firmware,retired_date,retirement_reason,current_soh_pct\nBAT-2W-100000,2W_2.1kWh,Cellora,CE-2503,2025-01-30,2025-03-19,2.1,31018,99.9,BMS-4.1,,,79.5\nBAT-2W-100001,2W_2.1kWh,Cellora,CE-2403,2024-02-27,2024-03-30,2.1,34111,99.2,BMS-4.2,,,79.5\nBAT-3W-100002,3W_4.8kWh,Cellora,CE-2305,2023-04-15,2023-05-11,4.8,66521,99.5,BMS-4.1,,,87.0\nBAT-2W-100003,2W_2.1kWh,Kyron,KY-2409,2024-09-28,2024-10-09,2.1,32753,99.5,BMS-4.1,2025-06-15,end_of_life,58.1\nBAT-2W-100004,2W_2.1kWh,Kyron,KY-2407,2024-11-06,2024-11-21,2.1,31734,99.5,BMS-4.2,2025-06-15,end_of_life,60.6\nBAT-2W-100005,2W_2.1kWh,Cellora,CE-2308,2023-07-18,2023-08-31,2.1,32340,99.2,BMS-4.2,,,80.5\nBAT-2W-100006,2W_2.1kWh,Kyron,KY-2408,2024-09-29,2024-10-20,2.1,31653,99.5,BMS-4.2,2025-06-15,end_of_life,60.5\nBAT-2W-100007,2W_2.1kWh,Cellora,CE-2403,2024-02-25,2024-03-18,2.1,33929,99.2,BMS-4.0,,,80.2\nBAT-2W-100008,2W_2.1kWh,Cellora,CE-2410,2024-09-08,2024-10-26,2.1,32747,99.5,BMS-4.0,,,80.4\nBAT-2W-100009,2W_2.1kWh,Cellora,CE-2505,2025-04-12,2025-05-30,2.1,30477,98.8,BMS-4.2,,,80.1\nBAT-2W-100010,2W_2.1kWh,Amptek,AM-2501,2024-12-31,2025-01-17,2.1,32128,98.9,BMS-4.0,,,79.8\nBAT-2W-100011,2W_2.1kWh,Cellora,CE-2311,2023-10-25,2023-11-28,2.1,33957,98.5,BMS-4.1,,,78.6\nBAT-2W-100012,2W_2.1kWh,Amptek,AM-2403,2024-02-20,2024-03-07,2.1,32391,98.8,BMS-4.2,,,79.6\nBAT-2W-100013,2W_2.1kWh,Amptek,AM-2406,2024-04-25,2024-06-02,2.1,33986,99.0,BMS-4.1,,,79.8\nBAT-2W-100014,2W_2.1kWh,Kyron,KY-2409,2024-09-27,2024-11-13,2.1,33323,99.6,BMS-4.1,2025-06-15,end_of_life,62.5\nBAT-2W-100015,2W_2.1kWh,Cellora,CE-2409,2024-08-31,2024-09-18,2.1,30800,99.3,BMS-4.0,,,80.0\nBAT-2W-100016,2W_2.1kWh,Kyron,KY-2408,2024-09-01,2024-09-14,2.1,29591,99.7,BMS-4.1,2025-06-15,end_of_life,58.6\nBAT-2W-100017,2W_2.1kWh,Amptek,AM-2405,2024-04-22,2024-05-25,2.1,33926,98.9,BMS-4.2,,,80.2\nBAT-2W-100018,2W_2.1kWh,Kyron,KY-2409,2024-08-12,2024-09-23,2.1,32922,99.0,BMS-4.1,2025-06-15,end_of_life,61.5\nBAT-2W-100019,2W_2.1kWh,Cellora,CE-2304,2023-04-03,2023-04-26,2.1,30812,99.0,BMS-4.1,,,80.4\nBAT-2W-100020,2W_2.1kWh,Cellora,CE-2311,2023-11-09,2023-11-25,2.1,31865,99.0,BMS-4.2,,,81.2\nBAT-3W-100021,3W_4.8kWh,Kyron,KY-2411,2024-09-20,2024-11-17,4.8,65541,99.2,BMS-4.1,,,86.7\nBAT-3W-100022,3W_4.8kWh,Cellora,CE-2410,2024-08-22,2024-10-03,4.8,65681,99.7,BMS-4.2,,,87.5\nBAT-2W-100023,2W_2.1kWh,Amptek,AM-2503,2025-03-12,2025-03-31,2.1,32867,99.3,BMS-4.0,,,80.5\nBAT-2W-100024,2W_2.1kWh,Cellora,CE-2412,2024-10-31,2024-12-04,2.1,31683,99.0,BMS-4.2,,,79.7\nBAT-2W-100025,2W_2.1kWh,Kyron,KY-2408,2024-09-21,2024-10-28,2.1,31485,99.4,BMS-4.0,2025-06-15,end_of_life,59.3\nBAT-2W-100026,2W_2.1kWh,Cellora,CE-2309,2023-08-25,2023-09-08,2.1,33301,99.8,BMS-4.1,,,81.6\nBAT-2W-100027,2W_2.1kWh,Kyron,KY-2409,2024-10-15,2024-11-28,2.1,33188,98.6,BMS-4.1,2025-06-15,end_of_life,60.1\nBAT-2W-100028,2W_2.1kWh,Cellora,CE-2502,2025-01-16,2025-02-21,2.1,32869,99.6,BMS-4.2,,,81.6\nBAT-3W-100029,3W_4.8kWh,Cellora,CE-2408,2024-08-16,2024-08-30,4.8,68494,100.0,BMS-4.1,,,87.6\nBAT-2W-100030,2W_2.1kWh,Amptek,AM-2503,2025-02-16,2025-03-22,2.1,34276,99.7,BMS-4.0,,,79.9\nBAT-2W-100031,2W_2.1kWh,Cellora,CE-2501,2024-12-31,2025-01-10,2.1,31949,98.4,BMS-4.2,,,79.4\nBAT-2W-100032,2W_2.1kWh,Cellora,CE-2306,2023-06-03,2023-06-21,2.1,31932,99.3,BMS-4.1,,,80.7\nBAT-2W-100033,2W_2.1kWh,Cellora,CE-2304,2023-02-20,2023-04-11,2.1,31048,99.2,BMS-4.0,,,80.5\nBAT-3W-100034,3W_4.8kWh,Kyron,KY-2414,2024-12-21,2025-02-18,4.8,62912,99.3,BMS-4.2,,,86.8\nBAT-2W-100035,2W_2.1kWh,Kyron,KY-2409,2024-10-27,2024-11-10,2.1,31808,98.8,BMS-4.1,2025-06-15,end_of_life,59.8\nBAT-3W-100036,3W_4.8kWh,Amptek,AM-2409,2024-08-16,2024-09-23,4.8,67531,98.4,BMS-4.2,,,85.4\nBAT-2W-100037,2W_2.1kWh,Cellora,CE-2408,2024-06-26,2024-08-04,2.1,31417,99.9,BMS-4.0,,,79.6\nBAT-3W-100038,3W_4.8kWh,Amptek,AM-2506,2025-06-01,2025-06-13,4.8,66778,99.1,BMS-4.1,,,87.3\nBAT-3W-100039,3W_4.8kWh,Cellora,CE-2304,2023-03-02,2023-04-03,4.8,65961,100.0,BMS-4.0,,,88.3\nBAT-2W-100040,2W_2.1kWh,Cellora,CE-2408,2024-06-30,2024-08-15,2.1,32592,99.1,BMS-4.0,,,80.1\nBAT-2W-100041,2W_2.1kWh,Cellora,CE-2505,2025-04-01,2025-05-24,2.1,33270,98.7,BMS-4.2,,,79.3\nBAT-2W-100042,2W_2.1kWh,Cellora,CE-2405,2024-03-20,2024-05-03,2.1,32452,98.8,BMS-4.1,,,77.9\nBAT-3W-100043,3W_4.8kWh,Amptek,AM-2406,2024-04-26,2024-06-11,4.8,66605,99.0,BMS-4.0,,,86.8\nBAT-2W-100044,2W_2.1kWh,Cellora,CE-2404,2024-02-06,2024-04-01,2.1,31144,99.6,BMS-4.1,,,80.6\nBAT-2W-100045,2W_2.1kWh,Cellora,CE-2505,2025-04-05,2025-05-21,2.1,32906,99.4,BMS-4.1,,,80.1\nBAT-3W-100046,3W_4.8kWh,Cellora,CE-2410,2024-09-02,2024-10-10,4.8,67703,98.9,BMS-4.0,,,86.4\nBAT-2W-100047,2W_2.1kWh,Amptek,AM-2405,2024-03-29,2024-05-05,2.1,32565,99.6,BMS-4.1,,,82.3\nBAT-2W-100048,2W_2.1kWh,Amptek,AM-2403,2024-02-02,2024-03-31,2.1,32152,99.1,BMS-4.2,,,80.6\nBAT-2W-100049,2W_2.1kWh,Kyron,KY-2407,2024-10-05,2024-10-17,2.1,33599,98.9,BMS-4.2,2025-06-15,end_of_life,59.2\nBAT-2W-100050,2W_2.1kWh,Amptek,AM-2502,2025-01-02,2025-02-17,2.1,31145,98.7,BMS-4.1,,,80.3\nBAT-2W-100051,2W_2.1kWh,Cellora,CE-2310,2023-09-23,2023-10-16,2.1,30520,99.3,BMS-4.0,,,79.6\nBAT-2W-100052,2W_2.1kWh,Cellora,CE-2411,2024-10-22,2024-11-29,2.1,32740,99.2,BMS-4.0,,,80.2\nBAT-2W-100053,2W_2.1kWh,Cellora,CE-2305,2023-05-02,2023-05-20,2.1,30127,99.4,BMS-4.1,,,80.5\nBAT-2W-100054,2W_2.1kWh,Kyron,KY-2408,2024-08-28,2024-09-28,2.1,31545,99.1,BMS-4.1,2025-06-15,end_of_life,63.0\nBAT-3W-100055,3W_4.8kWh,Cellora,CE-2503,2025-02-12,2025-03-23,4.8,66445,99.5,BMS-4.2,,,87.2\nBAT-2W-100056,2W_2.1kWh,Cellora,CE-2404,2024-03-21,2024-04-14,2.1,32830,98.6,BMS-4.0,,,79.8\nBAT-2W-100057,2W_2.1kWh,Amptek,AM-2404,2024-02-24,2024-04-07,2.1,32542,99.5,BMS-4.2,,,81.3\nBAT-2W-100058,2W_2.1kWh,Amptek,AM-2406,2024-05-22,2024-06-18,2.1,31500,99.6,BMS-4.2,,,80.4\nBAT-2W-100059,2W_2.1kWh,Cellora,CE-2306,2023-05-13,2023-06-11,2.1,32804,99.1,BMS-4.1,,,79.6\nBAT-2W-100060,2W_2.1kWh,Cellora,CE-2504,2025-03-11,2025-04-14,2.1,32327,99.7,BMS-4.2,,,79.8\nBAT-2W-100061,2W_2.1kWh,Amptek,AM-2409,2024-08-27,2024-09-10,2.1,33397,99.2,BMS-4.1,,,80.1\nBAT-2W-100062,2W_2.1kWh,Cellora,CE-2306,2023-05-22,2023-06-27,2.1,32183,99.3,BMS-4.0,,,79.1\nBAT-2W-100063,2W_2.1kWh,Cellora,CE-2303,2023-03-01,2023-03-13,2.1,32269,99.6,BMS-4.2,,,81.5\nBAT-2W-100064,2W_2.1kWh,Cellora,CE-2408,2024-07-05,2024-08-02,2.1,31115,99.1,BMS-4.2,,,80.4\nBAT-2W-100065,2W_2.1kWh,Cellora,CE-2402,2024-01-08,2024-02-22,2.1,33247,99.3,BMS-4.2,,,79.4\nBAT-2W-100066,2W_2.1kWh,Kyron,KY-2409,2024-10-10,2024-11-03,2.1,31475,99.0,BMS-4.1,2025-06-15,end_of_life,62.4\nBAT-2W-100067,2W_2.1kWh,Amptek,AM-2403,2024-01-15,2024-03-10,2.1,31393,98.8,BMS-4.2,,,79.7\nBAT-2W-100068,2W_2.1kWh,Amptek,AM-2410,2024-09-12,2024-10-24,2.1,31440,99.4,BMS-4.1,,,80.8\nBAT-3W-100069,3W_4.8kWh,Kyron,KY-2413,2024-12-17,2025-01-12,4.8,67473,99.0,BMS-4.1,,,85.9\nBAT-2W-100070,2W_2.1kWh,Cellora,CE-2306,2023-04-19,2023-06-06,2.1,32726,98.4,BMS-4.2,,,80.3\nBAT-3W-100071,3W_4.8kWh,Kyron,KY-2409,2024-08-17,2024-09-13,4.8,66738,99.5,BMS-4.2,,,71.3\nBAT-2W-100072,2W_2.1kWh,Cellora,CE-2311,2023-09-25,2023-11-15,2.1,31486,99.1,BMS-4.0,,,78.7\nBAT-3W-100073,3W_4.8kWh,Cellora,CE-2406,2024-06-18,2024-06-28,4.8,66849,99.7,BMS-4.0,,,86.2\nBAT-2W-100074,2W_2.1kWh,Cellora,CE-2405,2024-04-02,2024-05-28,2.1,31507,99.0,BMS-4.1,,,80.4\nBAT-2W-100075,2W_2.1kWh,Cellora,CE-2504,2025-03-22,2025-04-27,2.1,32283,99.3,BMS-4.0,,,78.3\nBAT-2W-100076,2W_2.1kWh,Cellora,CE-2503,2025-03-06,2025-03-21,2.1,32054,99.5,BMS-4.2,,,81.2\nBAT-3W-100077,3W_4.8kWh,Cellora,CE-2504,2025-03-14,2025-04-04,4.8,69724,99.2,BMS-4.2,,,86.3\nBAT-3W-100078,3W_4.8kWh,Cellora,CE-2309,2023-09-02,2023-09-26,4.8,67509,99.2,BMS-4.2,,,86.7\nBAT-2W-100079,2W_2.1kWh,Kyron,KY-2407,2024-10-13,2024-11-28,2.1,33368,98.9,BMS-4.1,2025-06-15,end_of_life,63.0\nBAT-2W-100080,2W_2.1kWh,Cellora,CE-2502,2024-12-05,2025-02-02,2.1,31846,99.2,BMS-4.1,,,81.0\nBAT-2W-100081,2W_2.1kWh,Cellora,CE-2409,2024-08-19,2024-09-05,2.1,31122,99.2,BMS-4.2,,,80.1\nBAT-3W-100082,3W_4.8kWh,Cellora,CE-2406,2024-04-19,2024-06-15,4.8,69463,99.4,BMS-4.2,,,86.2\nBAT-2W-100083,2W_2.1kWh,Amptek,AM-2504,2025-03-29,2025-04-23,2.1,31569,98.8,BMS-4.2,,,79.4\nBAT-2W-100084,2W_2.1kWh,Cellora,CE-2405,2024-04-03,2024-05-14,2.1,31781,99.3,BMS-4.1,,,79.4\nBAT-2W-100085,2W_2.1kWh,Cellora,CE-2505,2025-04-14,2025-05-04,2.1,32789,99.1,BMS-4.0,,,80.1\nBAT-2W-100086,2W_2.1kWh,Amptek,AM-2407,2024-05-29,2024-07-22,2.1,32045,99.0,BMS-4.2,,,79.7\nBAT-3W-100087,3W_4.8kWh,Amptek,AM-2503,2025-02-10,2025-03-30,4.8,70189,99.1,BMS-4.1,,,86.0\nBAT-2W-100088,2W_2.1kWh,Amptek,AM-2506,2025-04-29,2025-06-11,2.1,34234,99.6,BMS-4.1,,,79.1\nBAT-2W-100089,2W_2.1kWh,Cellora,CE-2405,2024-03-10,2024-05-04,2.1,31741,99.5,BMS-4.0,,,80.4\nBAT-2W-100090,2W_2.1kWh,Amptek,AM-2407,2024-05-19,2024-07-13,2.1,30864,99.3,BMS-4.1,,,80.6\nBAT-2W-100091,2W_2.1kWh,Cellora,CE-2410,2024-09-10,2024-10-07,2.1,31614,98.8,BMS-4.0,,,79.8\nBAT-2W-100092,2W_2.1kWh,Kyron,KY-2409,2024-10-24,2024-11-10,2.1,30584,99.1,BMS-4.2,2025-06-15,end_of_life,61.8\nBAT-3W-100093,3W_4.8kWh,Cellora,CE-2303,2023-01-22,2023-03-12,4.8,62738,99.6,BMS-4.1,,,87.0\nBAT-3W-100094,3W_4.8kWh,Cellora,CE-2410,2024-10-03,2024-10-23,4.8,68226,99.7,BMS-4.0,,,86.6\nBAT-2W-100095,2W_2.1kWh,Kyron,KY-2408,2024-11-20,2024-11-30,2.1,31219,99.2,BMS-4.2,2025-06-15,end_of_life,63.7\nBAT-2W-100096,2W_2.1kWh,Amptek,AM-2406,2024-04-12,2024-06-05,2.1,33613,99.2,BMS-4.0,,,80.1\nBAT-3W-100097,3W_4.8kWh,Amptek,AM-2412,2024-11-04,2024-12-02,4.8,68630,99.2,BMS-4.0,,,86.7\nBAT-2W-100098,2W_2.1kWh,Cellora,CE-2409,2024-08-04,2024-09-13,2.1,32581,99.0,BMS-4.2,,,80.1\nBAT-2W-100099,2W_2.1kWh,Kyron,KY-2408,2024-10-03,2024-10-22,2.1,32593,99.1,BMS-4.0,2025-06-15,end_of_life,61.2\nBAT-3W-100100,3W_4.8kWh,Cellora,CE-2504,2025-03-04,2025-04-27,4.8,70436,99.0,BMS-4.1,,,86.2\nBAT-2W-100101,2W_2.1kWh,Cellora,CE-2408,2024-07-10,2024-08-20,2.1,33036,98.8,BMS-4.1,,,79.0\nBAT-2W-100102,2W_2.1kWh,Amptek,AM-2405,2024-04-24,2024-05-17,2.1,32281,99.2,BMS-4.1,,,79.5\nBAT-3W-100103,3W_4.8kWh,Cellora,CE-2303,2023-02-04,2023-03-13,4.8,69617,99.0,BMS-4.2,,,86.5\nBAT-2W-100104,2W_2.1kWh,Kyron,KY-2409,2024-10-17,2024-11-12,2.1,32482,98.6,BMS-4.1,2025-06-15,end_of_life,60.0\nBAT-2W-100105,2W_2.1kWh,Cellora,CE-2309,2023-08-21,2023-09-22,2.1,31790,99.0,BMS-4.2,,,78.9\nBAT-2W-100106,2W_2.1kWh,Amptek,AM-2403,2024-01-25,2024-03-20,2.1,32783,99.6,BMS-4.1,,,80.4\nBAT-2W-100107,2W_2.1kWh,Amptek,AM-2505,2025-04-18,2025-05-14,2.1,31889,99.9,BMS-4.2,,,81.0\nBAT-2W-100108,2W_2.1kWh,Kyron,KY-2408,2024-09-16,2024-10-19,2.1,33035,99.4,BMS-4.2,2025-06-15,end_of_life,60.9\nBAT-2W-100109,2W_2.1kWh,Kyron,KY-2407,2024-09-06,2024-10-18,2.1,29901,98.6,BMS-4.0,2025-06-15,end_of_life,61.5\nBAT-2W-100110,2W_2.1kWh,Kyron,KY-2409,2024-09-05,2024-10-15,2.1,32658,99.5,BMS-4.1,2025-06-15,end_of_life,60.2\nBAT-2W-100111,2W_2.1kWh,Kyron,KY-2409,2024-09-05,2024-09-25,2.1,31838,99.4,BMS-4.1,2025-06-15,end_of_life,65.6\nBAT-2W-100112,2W_2.1kWh,Kyron,KY-2408,2024-09-19,2024-11-06,2.1,31967,99.0,BMS-4.2,2025-06-15,end_of_life,60.0\nBAT-2W-100113,2W_2.1kWh,Kyron,KY-2407,2024-08-17,2024-09-26,2.1,30885,99.2,BMS-4.1,2025-06-15,end_of_life,62.1\nBAT-2W-100114,2W_2.1kWh,Amptek,AM-2411,2024-10-26,2024-11-16,2.1,30103,98.6,BMS-4.1,,,78.8\nBAT-2W-100115,2W_2.1kWh,Cellora,CE-2406,2024-04-26,2024-06-08,2.1,32618,99.8,BMS-4.1,,,82.2\nBAT-2W-100116,2W_2.1kWh,Amptek,AM-2501,2024-12-16,2025-01-30,2.1,32477,99.5,BMS-4.2,,,80.1\nBAT-2W-100117,2W_2.1kWh,Amptek,AM-2410,2024-08-24,2024-10-01,2.1,29479,99.4,BMS-4.1,,,80.7\nBAT-2W-100118,2W_2.1kWh,Kyron,KY-2408,2024-10-15,2024-10-30,2.1,32237,99.2,BMS-4.1,2025-06-15,end_of_life,60.0\nBAT-2W-100119,2W_2.1kWh,Cellora,CE-2307,2023-06-12,2023-07-28,2.1,32065,98.9,BMS-4.1,,,79.1\nBAT-2W-100120,2W_2.1kWh,Kyron,KY-2409,2024-11-03,2024-11-18,2.1,32668,99.2,BMS-4.1,2025-06-15,end_of_life,59.7\nBAT-3W-100121,3W_4.8kWh,Cellora,CE-2309,2023-07-30,2023-09-17,4.8,72460,99.8,BMS-4.2,,,87.9\nBAT-2W-100122,2W_2.1kWh,Cellora,CE-2303,2023-02-22,2023-03-07,2.1,31179,99.2,BMS-4.2,,,80.5\nBAT-2W-100123,2W_2.1kWh,Cellora,CE-2407,2024-05-16,2024-07-13,2.1,32622,99.2,BMS-4.0,,,81.4\nBAT-2W-100124,2W_2.1kWh,Cellora,CE-2305,2023-04-29,2023-05-21,2.1,34719,99.2,BMS-4.2,,,80.6\nBAT-3W-100125,3W_4.8kWh,Kyron,KY-2416,2025-02-06,2025-04-03,4.8,68936,99.5,BMS-4.2,,,86.8\nBAT-2W-100126,2W_2.1kWh,Amptek,AM-2506,2025-05-22,2025-06-02,2.1,32266,99.2,BMS-4.2,,,81.4\nBAT-2W-100127,2W_2.1kWh,Cellora,CE-2306,2023-05-14,2023-06-29,2.1,32742,99.6,BMS-4.2,,,79.5\nBAT-2W-100128,2W_2.1kWh,Cellora,CE-2303,2023-02-21,2023-03-10,2.1,31932,99.7,BMS-4.2,,,81.5\nBAT-2W-100129,2W_2.1kWh,Kyron,KY-2407,2024-11-10,2024-11-24,2.1,33461,99.4,BMS-4.1,2025-06-15,end_of_life,59.4\nBAT-2W-100130,2W_2.1kWh,Kyron,KY-2409,2024-09-29,2024-10-12,2.1,32617,98.9,BMS-4.1,2025-06-15,end_of_life,57.2\nBAT-2W-100131,2W_2.1kWh,Cellora,CE-2311,2023-10-04,2023-11-09,2.1,33650,99.2,BMS-4.2,,,80.7\nBAT-2W-100132,2W_2.1kWh,Cellora,CE-2306,2023-05-18,2023-06-26,2.1,32583,98.9,BMS-4.2,,,79.4\nBAT-3W-100133,3W_4.8kWh,Cellora,CE-2501,2024-11-28,2025-01-20,4.8,69627,99.0,BMS-4.1,,,85.8\nBAT-2W-100134,2W_2.1kWh,Kyron,KY-2407,2024-10-08,2024-11-23,2.1,32736,99.5,BMS-4.1,2025-06-15,end_of_life,61.3\nBAT-2W-100135,2W_2.1kWh,Kyron,KY-2408,2024-11-01,2024-11-14,2.1,30449,99.4,BMS-4.2,2025-06-15,end_of_life,59.0\nBAT-2W-100136,2W_2.1kWh,Cellora,CE-2412,2024-11-09,2024-12-18,2.1,31909,99.2,BMS-4.2,,,80.4\nBAT-3W-100137,3W_4.8kWh,Kyron,KY-2409,2024-07-26,2024-09-14,4.8,71448,99.9,BMS-4.1,,,70.0\nBAT-3W-100138,3W_4.8kWh,Cellora,CE-2310,2023-09-18,2023-10-18,4.8,65671,99.5,BMS-4.2,,,87.4\nBAT-2W-100139,2W_2.1kWh,Kyron,KY-2409,2024-09-18,2024-10-25,2.1,31174,99.4,BMS-4.0,2025-06-15,end_of_life,61.8\nBAT-2W-100140,2W_2.1kWh,Amptek,AM-2501,2024-12-28,2025-01-31,2.1,31348,99.1,BMS-4.2,,,80.0\nBAT-2W-100141,2W_2.1kWh,Kyron,KY-2407,2024-08-25,2024-09-23,2.1,31238,98.0,BMS-4.0,2025-06-15,end_of_life,60.7\nBAT-2W-100142,2W_2.1kWh,Kyron,KY-2408,2024-09-02,2024-10-20,2.1,28908,98.6,BMS-4.2,2025-06-15,end_of_life,58.5\nBAT-3W-100143,3W_4.8kWh,Kyron,KY-2411,2024-10-10,2024-11-26,4.8,68437,98.9,BMS-4.2,,,85.7\nBAT-3W-100144,3W_4.8kWh,Kyron,KY-2418,2025-04-29,2025-06-15,4.8,66236,99.5,BMS-4.1,,,87.2\nBAT-3W-100145,3W_4.8kWh,Kyron,KY-2418,2025-05-05,2025-06-14,4.8,68687,99.4,BMS-4.1,,,87.3\nBAT-2W-100146,2W_2.1kWh,Cellora,CE-2403,2024-02-04,2024-03-10,2.1,31685,98.2,BMS-4.2,,,79.6\nBAT-2W-100147,2W_2.1kWh,Amptek,AM-2505,2025-05-05,2025-05-31,2.1,30683,98.9,BMS-4.2,,,80.1\nBAT-2W-100148,2W_2.1kWh,Amptek,AM-2403,2024-01-27,2024-03-17,2.1,32391,99.2,BMS-4.0,,,81.7\nBAT-2W-100149,2W_2.1kWh,Amptek,AM-2408,2024-07-18,2024-08-15,2.1,31930,99.0,BMS-4.2,,,81.2\nBAT-2W-100150,2W_2.1kWh,Cellora,CE-2304,2023-03-05,2023-04-15,2.1,34463,99.2,BMS-4.0,,,80.9\nBAT-2W-100151,2W_2.1kWh,Amptek,AM-2410,2024-08-28,2024-10-24,2.1,33847,99.6,BMS-4.2,,,79.9\nBAT-2W-100152,2W_2.1kWh,Cellora,CE-2407,2024-07-15,2024-07-30,2.1,32130,99.3,BMS-4.1,,,79.9\nBAT-2W-100153,2W_2.1kWh,Cellora,CE-2401,2023-11-29,2024-01-14,2.1,32682,99.4,BMS-4.0,,,81.0\nBAT-2W-100154,2W_2.1kWh,Cellora,CE-2503,2025-02-11,2025-03-27,2.1,30661,98.0,BMS-4.2,,,79.6\nBAT-3W-100155,3W_4.8kWh,Kyron,KY-2412,2024-10-14,2024-12-07,4.8,71521,99.1,BMS-4.2,,,85.3\nBAT-2W-100156,2W_2.1kWh,Kyron,KY-2409,2024-09-28,2024-11-01,2.1,33318,99.6,BMS-4.1,2025-06-15,end_of_life,57.9\nBAT-2W-100157,2W_2.1kWh,Cellora,CE-2409,2024-07-05,2024-09-02,2.1,31769,99.4,BMS-4.0,,,81.0\nBAT-2W-100158,2W_2.1kWh,Cellora,CE-2307,2023-07-17,2023-07-29,2.1,32271,99.4,BMS-4.1,,,79.5\nBAT-2W-100159,2W_2.1kWh,Kyron,KY-2409,2024-09-10,2024-10-27,2.1,29790,98.6,BMS-4.2,2025-06-15,end_of_life,57.3\nBAT-2W-100160,2W_2.1kWh,Cellora,CE-2412,2024-10-28,2024-12-11,2.1,30073,99.5,BMS-4.2,,,79.7\nBAT-2W-100161,2W_2.1kWh,Cellora,CE-2405,2024-05-02,2024-05-23,2.1,33103,100.0,BMS-4.2,,,81.7\nBAT-2W-100162,2W_2.1kWh,Cellora,CE-2401,2023-12-18,2024-01-04,2.1,32816,99.3,BMS-4.0,,,80.9\nBAT-2W-100163,2W_2.1kWh,Amptek,AM-2504,2025-03-16,2025-04-25,2.1,33278,99.6,BMS-4.0,,,81.0\nBAT-2W-100164,2W_2.1kWh,Cellora,CE-2401,2023-11-15,2024-01-06,2.1,31399,98.9,BMS-4.1,,,79.7\nBAT-2W-100165,2W_2.1kWh,Cellora,CE-2412,2024-11-05,2024-12-24,2.1,30622,99.5,BMS-4.0,,,79.4\nBAT-2W-100166,2W_2.1kWh,Amptek,AM-2408,2024-06-27,2024-08-10,2.1,32697,98.2,BMS-4.1,,,78.1\nBAT-2W-100167,2W_2.1kWh,Amptek,AM-2406,2024-05-25,2024-06-04,2.1,32406,99.1,BMS-4.0,,,79.9\nBAT-3W-100168,3W_4.8kWh,Kyron,KY-2417,2025-04-09,2025-05-26,4.8,65498,100.0,BMS-4.2,,,87.3\nBAT-2W-100169,2W_2.1kWh,Cellora,CE-2502,2024-12-23,2025-02-01,2.1,30267,98.3,BMS-4.1,,,77.7\nBAT-2W-100170,2W_2.1kWh,Cellora,CE-2409,2024-09-08,2024-09-20,2.1,30853,99.2,BMS-4.0,,,79.2\nBAT-2W-100171,2W_2.1kWh,Cellora,CE-2407,2024-06-07,2024-07-21,2.1,30785,99.6,BMS-4.0,,,79.9\nBAT-3W-100172,3W_4.8kWh,Amptek,AM-2408,2024-06-05,2024-08-01,4.8,67237,100.0,BMS-4.1,,,85.4\nBAT-2W-100173,2W_2.1kWh,Amptek,AM-2506,2025-05-01,2025-06-13,2.1,31372,99.3,BMS-4.2,,,81.5\nBAT-2W-100174,2W_2.1kWh,Cellora,CE-2310,2023-08-16,2023-10-12,2.1,32598,99.6,BMS-4.0,,,80.4\nBAT-2W-100175,2W_2.1kWh,Kyron,KY-2409,2024-10-01,2024-10-12,2.1,32461,99.0,BMS-4.1,2025-06-15,end_of_life,58.4\nBAT-2W-100176,2W_2.1kWh,Amptek,AM-2407,2024-07-12,2024-07-31,2.1,30672,98.8,BMS-4.2,,,78.5\nBAT-2W-100177,2W_2.1kWh,Cellora,CE-2308,2023-07-16,2023-08-06,2.1,30910,100.0,BMS-4.1,,,80.5\nBAT-2W-100178,2W_2.1kWh,Cellora,CE-2502,2025-01-31,2025-02-28,2.1,31092,99.6,BMS-4.1,,,79.5\nBAT-2W-100179,2W_2.1kWh,Kyron,KY-2407,2024-10-16,2024-11-28,2.1,31245,99.8,BMS-4.1,2025-06-15,end_of_life,63.2\nBAT-2W-100180,2W_2.1kWh,Kyron,KY-2407,2024-10-14,2024-11-11,2.1,30048,99.1,BMS-4.0,2025-06-15,end_of_life,63.4\nBAT-3W-100181,3W_4.8kWh,Kyron,KY-2407,2024-05-28,2024-07-07,4.8,68565,98.9,BMS-4.0,2025-06-15,end_of_life,67.1\nBAT-2W-100182,2W_2.1kWh,Cellora,CE-2405,2024-04-07,2024-05-29,2.1,34358,98.6,BMS-4.2,,,79.1\nBAT-2W-100183,2W_2.1kWh,Kyron,KY-2408,2024-10-02,2024-11-10,2.1,33697,98.8,BMS-4.1,2025-06-15,end_of_life,61.7\nBAT-3W-100184,3W_4.8kWh,Amptek,AM-2405,2024-05-18,2024-05-30,4.8,66322,99.1,BMS-4.2,,,86.4\nBAT-2W-100185,2W_2.1kWh,Kyron,KY-2407,2024-09-09,2024-09-23,2.1,31220,98.7,BMS-4.0,2025-06-15,end_of_life,59.8\nBAT-3W-100186,3W_4.8kWh,Cellora,CE-2504,2025-03-30,2025-04-12,4.8,61873,99.6,BMS-4.1,,,86.3\nBAT-3W-100187,3W_4.8kWh,Cellora,CE-2501,2024-12-10,2025-01-12,4.8,72189,98.6,BMS-4.0,,,85.9\nBAT-2W-100188,2W_2.1kWh,Cellora,CE-2311,2023-09-25,2023-11-01,2.1,31313,98.3,BMS-4.1,,,79.5\nBAT-2W-100189,2W_2.1kWh,Kyron,KY-2407,2024-09-12,2024-10-31,2.1,32271,98.5,BMS-4.1,2025-06-15,end_of_life,59.7\nBAT-2W-100190,2W_2.1kWh,Cellora,CE-2405,2024-03-22,2024-05-20,2.1,32773,98.9,BMS-4.1,,,79.6\nBAT-2W-100191,2W_2.1kWh,Kyron,KY-2408,2024-09-15,2024-10-23,2.1,32383,98.7,BMS-4.0,2025-06-15,end_of_life,57.2\nBAT-2W-100192,2W_2.1kWh,Cellora,CE-2406,2024-05-13,2024-06-19,2.1,32771,99.6,BMS-4.0,,,79.4\nBAT-2W-100193,2W_2.1kWh,Kyron,KY-2408,2024-09-09,2024-10-22,2.1,32690,98.8,BMS-4.1,2025-06-15,end_of_life,60.7\nBAT-3W-100194,3W_4.8kWh,Cellora,CE-2411,2024-10-04,2024-11-09,4.8,65536,99.3,BMS-4.1,,,87.2\nBAT-2W-100195,2W_2.1kWh,Kyron,KY-2409,2024-08-28,2024-09-22,2.1,31142,99.0,BMS-4.0,2025-06-15,end_of_life,63.0\nBAT-3W-100196,3W_4.8kWh,Cellora,CE-2406,2024-05-21,2024-06-30,4.8,66801,98.4,BMS-4.1,,,86.2\nBAT-2W-100197,2W_2.1kWh,Amptek,AM-2412,2024-11-23,2024-12-05,2.1,30784,99.2,BMS-4.1,,,81.2\nBAT-2W-100198,2W_2.1kWh,Amptek,AM-2501,2024-11-21,2025-01-18,2.1,32026,99.0,BMS-4.2,,,80.2\nBAT-2W-100199,2W_2.1kWh,Cellora,CE-2412,2024-11-11,2024-12-05,2.1,32474,99.4,BMS-4.0,,,79.4\nBAT-2W-100200,2W_2.1kWh,Cellora,CE-2407,2024-05-29,2024-07-25,2.1,32047,99.1,BMS-4.2,,,79.7\nBAT-2W-100201,2W_2.1kWh,Amptek,AM-2506,2025-04-28,2025-06-14,2.1,30510,99.1,BMS-4.2,,,79.6\nBAT-2W-100202,2W_2.1kWh,Kyron,KY-2408,2024-08-28,2024-10-01,2.1,32146,98.8,BMS-4.0,2025-06-15,end_of_life,61.5\nBAT-2W-100203,2W_2.1kWh,Kyron,KY-2408,2024-09-08,2024-10-18,2.1,31508,99.3,BMS-4.1,2025-06-15,end_of_life,61.

# EDA PART OF THE DATA

In [92]:
df = pd.read_csv("batteries.csv")
df
print(df.shape)
print(df.info())

(6500, 13)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6500 entries, 0 to 6499
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   battery_id          6500 non-null   object
 1   pack_type           6500 non-null   object
 2   supplier            6500 non-null   object
 3   manufacturing_lot   6500 non-null   object
 4   manufacture_date    6500 non-null   object
 5   commission_date     6500 non-null   object
 6   rated_capacity_kwh  6500 non-null   float64
 7   purchase_cost_inr   6500 non-null   int64
 8   initial_soh_pct     6500 non-null   float64
 9   bms_firmware        6500 non-null   object
 10  retired_date        1438 non-null   object
 11  retirement_reason   1438 non-null   object
 12  current_soh_pct     6500 non-null   float64
dtypes: float64(3), int64(1), object(9)
memory usage: 660.3+ KB
None

In [93]:
df.head()

,battery_id,pack_type,supplier,manufacturing_lot,manufacture_date,commission_date,rated_capacity_kwh,purchase_cost_inr,initial_soh_pct,bms_firmware,retired_date,retirement_reason,current_soh_pct
0,BAT-2W-100000,2W_2.1kWh,Cellora,CE-2503,2025-01-30,2025-03-19,2.1,31018,99.9,BMS-4.1,NaN,NaN,79.5
1,BAT-2W-100001,2W_2.1kWh,Cellora,CE-2403,2024-02-27,2024-03-30,2.1,34111,99.2,BMS-4.2,NaN,NaN,79.5
2,BAT-3W-100002,3W_4.8kWh,Cellora,CE-2305,2023-04-15,2023-05-11,4.8,66521,99.5,BMS-4.1,NaN,NaN,87.0
3,BAT-2W-100003,2W_2.1kWh,Kyron,KY-2409,2024-09-28,2024-10-09,2.1,32753,99.5,BMS-4.1,2025-06-15,end_of_life,58.1
4,BAT-2W-100004,2W_2.1kWh,Kyron,KY-2407,2024-11-06,2024-11-21,2.1,31734,99.5,BMS-4.2,2025-06-15,end_of_life,60.6

In [94]:
df.tail()

,battery_id,pack_type,supplier,manufacturing_lot,manufacture_date,commission_date,rated_capacity_kwh,purchase_cost_inr,initial_soh_pct,bms_firmware,retired_date,retirement_reason,current_soh_pct
6495,BAT-2W-106495,2W_2.1kWh,Kyron,KY-2408,2024-10-22,2024-11-30,2.1,32313,98.6,BMS-4.1,2025-06-15,end_of_life,61.2
6496,BAT-2W-106496,2W_2.1kWh,Kyron,KY-2409,2024-10-22,2024-11-19,2.1,30867,99.9,BMS-4.0,2025-06-15,end_of_life,63.2
6497,BAT-2W-106497,2W_2.1kWh,Cellora,CE-2412,2024-12-03,2024-12-30,2.1,30607,99.6,BMS-4.1,NaN,NaN,81.5
6498,BAT-2W-106498,2W_2.1kWh,Kyron,KY-2408,2024-11-05,2024-11-22,2.1,31885,100.0,BMS-4.2,2025-06-15,end_of_life,63.5
6499,BAT-2W-106499,2W_2.1kWh,Kyron,KY-2407,2024-09-11,2024-10-29,2.1,33063,98.5,BMS-4.0,2025-06-15,end_of_life,60.4

# FINDING MISSING VALUES AND DUPLICATES

In [95]:
df.isnull().sum()

battery_id               0
pack_type                0
supplier                 0
manufacturing_lot        0
manufacture_date         0
commission_date          0
rated_capacity_kwh       0
purchase_cost_inr        0
initial_soh_pct          0
bms_firmware             0
retired_date          5062
retirement_reason     5062
current_soh_pct          0
dtype: int64

In [96]:
df.dtypes

battery_id             object
pack_type              object
supplier               object
manufacturing_lot      object
manufacture_date       object
commission_date        object
rated_capacity_kwh    float64
purchase_cost_inr       int64
initial_soh_pct       float64
bms_firmware           object
retired_date           object
retirement_reason      object
current_soh_pct       float64
dtype: object

In [97]:
df.shape

(6500, 13)

In [98]:
df.size

84500

In [99]:
df.duplicated().sum()

np.int64(0)

In [100]:
df.describe()

       rated_capacity_kwh  purchase_cost_inr  initial_soh_pct  current_soh_pct
count         6500.000000        6500.000000      6500.000000      6500.000000
mean             2.507908       37414.073538        99.191292        76.614585
std              0.967009       12951.496627         0.397470         8.824758
min              2.100000       27473.000000        97.800000        55.400000
25%              2.100000       31339.500000        98.900000        78.400000
50%              2.100000       32250.000000        99.200000        79.800000
75%              2.100000       33397.250000        99.500000        80.800000
max              4.800000       75037.000000       100.000000        88.600000

In [101]:
for col in df.select_dtypes(include=["object","string"]).columns:
    s = df[col].dropna().astype(str)
    print(col, (s != s.str.strip()).sum())  # checking the Text columns  extra space

battery_id 0
pack_type 0
supplier 0
manufacturing_lot 0
manufacture_date 0
commission_date 0
bms_firmware 0
retired_date 0
retirement_reason 0

# CELANING THE DATASET

In [102]:
for col in ["manufacture_date", "commission_date", "retired_date"]:
    df[col] = pd.to_datetime(df[col], errors="coerce")
print(df["manufacture_date"].dtype)

datetime64[ns]

In [103]:
df["status"] = df["retired_date"].apply(lambda x: "retired" if pd.notna(x) else "active")

In [104]:
df["retirement_reason"] = df["retirement_reason"].fillna("active")

# CHECKING THE THE LOGICAL ORDER

In [105]:
print((df["commission_date"] < df["manufacture_date"]).sum()) # Retired date commission date ke baad honi chahiye

0

In [106]:
print((df["retired_date"] < df["commission_date"]).sum()) # Retired date commission date ke baad honi chahiye

0

In [107]:
print(((df["current_soh_pct"] < 0) | (df["current_soh_pct"] > 100)).sum()) #SOH (State of Health) percentage 0-100 range me hai kya

0

In [108]:
print((df["current_soh_pct"] > df["initial_soh_pct"]).sum()) #Current SOH kabhi initial SOH se zyada nahi honi chahiye (battery time ke saath degrade hoti hai)

0

In [109]:
print((df["purchase_cost_inr"] <= 0).sum())  # Cost negative ya zero to nahi

0

# FINAL DATA TYPE CONFIRM AND MISSING VALUES

In [110]:
df["purchase_cost_inr"] = df["purchase_cost_inr"].astype(int)
df["rated_capacity_kwh"] = df["rated_capacity_kwh"].astype(float)
print(df.dtypes)

battery_id                    object
pack_type                     object
supplier                      object
manufacturing_lot             object
manufacture_date      datetime64[ns]
commission_date       datetime64[ns]
rated_capacity_kwh           float64
purchase_cost_inr              int64
initial_soh_pct              float64
bms_firmware                  object
retired_date          datetime64[ns]
retirement_reason             object
current_soh_pct              float64
status                        object
dtype: object

In [111]:
df.isnull().sum()

battery_id               0
pack_type                0
supplier                 0
manufacturing_lot        0
manufacture_date         0
commission_date          0
rated_capacity_kwh       0
purchase_cost_inr        0
initial_soh_pct          0
bms_firmware             0
retired_date          5062
retirement_reason        0
current_soh_pct          0
status                   0
dtype: int64

In [112]:
df.to_csv("batteries_cleaned.csv", index=False)

# CITY DAILY DATASET

In [120]:
from google.colab import files
files.upload()

Saving city_daily_context.csv to city_daily_context (1).csv

{'city_daily_context (1).csv': b'city,date,max_temp_c,min_temp_c,rainfall_mm,heat_alert,flood_disruption,festival_or_event,is_public_holiday,grid_outage_hours,competitor_promo_active,ecommerce_sale_event\nBengaluru,2024-01-01,16.7,6.7,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-01-02,17.3,4.6,1.8,False,False,,False,0.2,False,False\nBengaluru,2024-01-03,13.9,6.9,0.7,False,False,,False,0.0,False,False\nBengaluru,2024-01-04,17.9,4.0,2.2,False,False,,False,0.1,False,False\nBengaluru,2024-01-05,16.0,7.8,2.0,False,False,,False,0.0,False,False\nBengaluru,2024-01-06,17.6,7.9,0.0,False,False,,False,0.1,False,False\nBengaluru,2024-01-07,17.2,8.2,0.0,False,False,,False,0.1,False,False\nBengaluru,2024-01-08,16.6,4.9,0.3,False,False,,False,0.3,False,False\nBengaluru,2024-01-09,16.8,8.2,0.0,False,False,,False,0.1,False,False\nBengaluru,2024-01-10,17.0,7.2,1.0,False,False,,False,0.2,False,False\nBengaluru,2024-01-11,16.8,5.6,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-01-12,18.5,4.9,0.0,False,False,,False,0.2,False,False\nBengaluru,2024-01-13,17.6,5.8,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-01-14,17.7,6.3,0.0,False,False,,False,0.2,False,False\nBengaluru,2024-01-15,14.4,5.5,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-01-16,17.2,5.8,0.7,False,False,,False,0.0,False,False\nBengaluru,2024-01-17,18.0,6.3,0.8,False,False,,False,0.1,False,False\nBengaluru,2024-01-18,13.6,6.6,0.1,False,False,,False,0.0,False,False\nBengaluru,2024-01-19,16.5,8.1,1.6,False,False,,False,0.0,False,False\nBengaluru,2024-01-20,19.5,7.8,0.0,False,False,,False,0.1,False,False\nBengaluru,2024-01-21,15.7,7.2,2.3,False,False,,False,0.2,False,False\nBengaluru,2024-01-22,15.4,7.8,0.3,False,False,,False,0.4,False,False\nBengaluru,2024-01-23,18.5,8.2,0.9,False,False,,False,0.2,False,False\nBengaluru,2024-01-24,13.0,8.2,0.2,False,False,,False,0.1,False,False\nBengaluru,2024-01-25,14.9,6.9,10.9,False,False,,False,0.1,False,False\nBengaluru,2024-01-26,15.4,7.4,1.1,False,False,,False,0.0,False,False\nBengaluru,2024-01-27,17.7,7.6,1.8,False,False,,False,0.2,False,False\nBengaluru,2024-01-28,20.1,7.5,1.3,False,False,,False,0.1,False,False\nBengaluru,2024-01-29,17.2,7.4,0.5,False,False,,False,0.1,False,False\nBengaluru,2024-01-30,17.9,8.8,1.2,False,False,,False,0.1,False,False\nBengaluru,2024-01-31,17.6,5.6,0.0,False,False,,False,0.1,False,False\nBengaluru,2024-02-01,18.6,5.4,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-02-02,19.1,10.3,0.3,False,False,,False,0.1,False,False\nBengaluru,2024-02-03,22.2,6.3,0.0,False,False,,False,0.2,False,False\nBengaluru,2024-02-04,15.7,8.7,0.0,False,False,,False,0.1,False,False\nBengaluru,2024-02-05,17.6,8.6,0.3,False,False,,False,0.3,False,False\nBengaluru,2024-02-06,17.7,6.9,1.3,False,False,,False,0.1,False,False\nBengaluru,2024-02-07,19.7,6.7,1.4,False,False,,False,0.1,False,False\nBengaluru,2024-02-08,19.9,9.4,0.4,False,False,,False,0.1,False,False\nBengaluru,2024-02-09,19.5,8.0,0.0,False,False,,False,0.1,False,False\nBengaluru,2024-02-10,17.3,7.8,1.8,False,False,,False,0.0,False,False\nBengaluru,2024-02-11,17.9,9.9,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-02-12,16.8,7.3,0.0,False,False,,False,0.4,False,False\nBengaluru,2024-02-13,16.1,8.3,2.5,False,False,,False,0.0,False,False\nBengaluru,2024-02-14,20.0,6.1,0.4,False,False,,False,0.0,False,False\nBengaluru,2024-02-15,20.4,7.1,3.0,False,False,,False,0.0,False,False\nBengaluru,2024-02-16,19.5,7.2,0.9,False,False,,False,0.2,False,False\nBengaluru,2024-02-17,20.6,7.1,3.1,False,False,,False,0.0,False,False\nBengaluru,2024-02-18,18.1,10.5,2.1,False,False,,False,0.2,False,False\nBengaluru,2024-02-19,18.2,7.9,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-02-20,17.3,8.5,0.0,False,False,,False,0.1,False,False\nBengaluru,2024-02-21,18.8,6.7,0.0,False,False,,False,0.1,False,False\nBengaluru,2024-02-22,17.4,6.3,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-02-23,20.4,7.2,0.0,False,False,,False,0.1,False,False\nBengaluru,2024-02-24,16.3,9.7,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-02-25,20.7,7.0,0.0,False,False,,False,0.1,False,False\nBengaluru,2024-02-26,18.9,6.3,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-02-27,18.3,7.4,0.0,False,False,,False,0.1,False,False\nBengaluru,2024-02-28,17.1,8.0,0.1,False,False,,False,0.2,False,False\nBengaluru,2024-02-29,18.9,5.5,0.9,False,False,,False,0.2,False,False\nBengaluru,2024-03-01,23.7,8.0,1.8,False,False,,False,0.1,False,False\nBengaluru,2024-03-02,20.0,10.0,6.5,False,False,,False,0.0,False,False\nBengaluru,2024-03-03,24.2,8.7,1.1,False,False,,False,0.1,False,False\nBengaluru,2024-03-04,24.5,10.0,3.2,False,False,,False,0.4,False,False\nBengaluru,2024-03-05,23.8,9.6,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-03-06,23.5,9.7,3.5,False,False,,False,0.1,False,False\nBengaluru,2024-03-07,23.7,8.7,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-03-08,22.5,10.3,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-03-09,22.8,9.6,0.3,False,False,,False,0.1,False,False\nBengaluru,2024-03-10,22.9,10.7,4.3,False,False,,False,0.4,False,False\nBengaluru,2024-03-11,24.5,7.9,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-03-12,27.6,8.0,0.0,False,False,,False,0.2,False,False\nBengaluru,2024-03-13,22.2,10.2,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-03-14,25.0,8.8,0.0,False,False,,False,0.1,False,False\nBengaluru,2024-03-15,21.9,9.2,0.0,False,False,,False,0.2,False,False\nBengaluru,2024-03-16,24.1,8.7,0.0,False,False,,False,0.1,False,False\nBengaluru,2024-03-17,23.5,10.2,4.6,False,False,,False,0.0,False,False\nBengaluru,2024-03-18,22.8,9.8,0.3,False,False,,False,0.0,False,False\nBengaluru,2024-03-19,22.3,8.9,0.6,False,False,,False,0.2,False,False\nBengaluru,2024-03-20,21.1,9.6,0.4,False,False,,False,0.1,False,False\nBengaluru,2024-03-21,22.2,10.3,0.7,False,False,,False,0.1,False,False\nBengaluru,2024-03-22,25.9,8.7,0.4,False,False,,False,0.1,False,False\nBengaluru,2024-03-23,24.5,8.0,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-03-24,21.3,11.4,0.7,False,False,,False,0.0,False,False\nBengaluru,2024-03-25,23.9,6.7,0.8,False,False,Holi,True,0.0,False,False\nBengaluru,2024-03-26,23.2,9.4,0.6,False,False,,False,0.1,False,False\nBengaluru,2024-03-27,24.3,9.9,0.0,False,False,,False,0.1,False,False\nBengaluru,2024-03-28,22.3,8.3,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-03-29,24.6,7.4,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-03-30,25.6,10.7,0.4,False,False,,False,0.0,False,False\nBengaluru,2024-03-31,21.6,11.2,0.0,False,False,,False,0.1,False,False\nBengaluru,2024-04-01,30.2,11.3,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-04-02,31.5,11.9,1.5,False,False,,False,0.1,False,False\nBengaluru,2024-04-03,29.5,12.0,0.0,False,False,,False,0.1,False,False\nBengaluru,2024-04-04,30.2,11.9,1.7,False,False,,False,0.1,False,False\nBengaluru,2024-04-05,30.6,12.4,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-04-06,29.9,13.0,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-04-07,29.7,13.5,0.0,False,False,,False,0.1,False,False\nBengaluru,2024-04-08,31.5,13.2,4.9,False,False,,False,0.0,False,False\nBengaluru,2024-04-09,29.1,11.6,0.0,False,False,,False,0.2,False,False\nBengaluru,2024-04-10,30.8,11.8,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-04-11,28.4,10.5,0.1,False,False,,False,0.3,False,False\nBengaluru,2024-04-12,33.4,12.3,0.3,False,False,,False,0.0,False,False\nBengaluru,2024-04-13,32.8,11.4,0.3,False,False,,False,0.1,False,False\nBengaluru,2024-04-14,30.4,12.4,0.0,False,False,,False,0.1,False,False\nBengaluru,2024-04-15,30.7,10.6,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-04-16,30.0,14.1,0.0,False,False,,False,0.2,False,False\nBengaluru,2024-04-17,27.2,12.3,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-04-18,30.0,11.1,0.0,False,False,,False,0.1,False,False\nBengaluru,2024-04-19,31.7,12.6,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-04-20,31.5,12.5,0.0,False,False,,False,0.1,False,False\nBengaluru,2024-04-21,30.7,12.4,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-04-22,30.0,11.3,3.8,False,False,,False,0.0,False,False\nBengaluru,2024-04-23,32.9,11.9,2.1,False,False,,False,0.2,False,False\nBengaluru,2024-04-24,30.5,13.5,1.6,False,False,,False,0.1,False,False\nBengaluru,2024-04-25,30.7,12.8,0.0,False,False,,False,0.1,False,False\nBengaluru,2024-04-26,32.5,12.6,0.0,False,False,,False,0.1,False,False\nBengaluru,2024-04-27,30.3,12.5,3.0,False,False,,False,0.2,False,False\nBengaluru,2024-04-28,31.9,11.2,0.0,False,False,,False,0.2,False,False\nBengaluru,2024-04-29,28.3,12.8,0.0,False,False,,False,0.2,False,False\nBengaluru,2024-04-30,30.2,13.9,0.0,False,False,,False,0.1,False,False\nBengaluru,2024-05-01,33.7,15.1,0.0,False,False,,False,0.1,False,False\nBengaluru,2024-05-02,33.5,14.7,0.7,False,False,,False,0.2,False,False\nBengaluru,2024-05-03,33.8,14.9,0.0,False,False,,False,0.1,False,False\nBengaluru,2024-05-04,32.9,14.2,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-05-05,35.5,12.1,0.3,False,False,,False,0.0,False,False\nBengaluru,2024-05-06,37.8,14.6,0.7,False,False,,False,0.2,False,False\nBengaluru,2024-05-07,35.8,12.5,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-05-08,36.1,13.5,0.8,False,False,,False,0.0,False,False\nBengaluru,2024-05-09,33.4,15.3,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-05-10,36.3,12.3,1.8,False,False,,False,0.1,False,False\nBengaluru,2024-05-11,32.3,14.0,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-05-12,36.9,15.0,0.0,False,False,,False,0.4,False,False\nBengaluru,2024-05-13,35.1,13.0,2.2,False,False,,False,0.0,False,False\nBengaluru,2024-05-14,33.9,12.2,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-05-15,38.2,13.6,0.0,False,False,,False,0.1,False,False\nBengaluru,2024-05-16,33.6,15.3,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-05-17,34.2,13.6,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-05-18,33.6,12.0,2.2,False,False,,False,0.1,False,False\nBengaluru,2024-05-19,35.4,15.5,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-05-20,36.9,14.2,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-05-21,35.5,13.5,0.0,False,False,,False,0.2,False,False\nBengaluru,2024-05-22,33.4,14.5,0.3,False,False,,False,0.1,False,False\nBengaluru,2024-05-23,30.5,13.4,0.0,False,False,,False,0.1,False,False\nBengaluru,2024-05-24,34.9,14.3,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-05-25,34.4,12.9,0.0,False,False,,False,0.1,False,False\nBengaluru,2024-05-26,33.5,13.4,0.6,False,False,,False,0.1,False,False\nBengaluru,2024-05-27,34.8,14.3,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-05-28,34.4,13.7,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-05-29,36.2,13.8,0.7,False,False,,False,0.0,False,False\nBengaluru,2024-05-30,37.5,13.9,0.0,False,False,,False,0.1,False,False\nBengaluru,2024-05-31,33.0,14.4,1.1,False,False,,False,0.1,False,False\nBengaluru,2024-06-01,34.1,14.9,17.3,False,False,,False,0.0,False,False\nBengaluru,2024-06-02,30.7,11.8,1.7,False,False,,False,0.1,False,False\nBengaluru,2024-06-03,32.0,13.1,6.2,False,False,,False,0.0,False,False\nBengaluru,2024-06-04,32.8,13.7,7.2,False,False,,False,0.0,False,False\nBengaluru,2024-06-05,33.7,12.6,7.6,False,False,,False,0.1,False,False\nBengaluru,2024-06-06,30.7,13.2,22.2,False,False,,False,0.1,False,False\nBengaluru,2024-06-07,30.1,11.5,0.0,False,False,,False,0.1,False,False\nBengaluru,2024-06-08,30.8,12.3,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-06-09,33.6,14.5,36.3,False,False,,False,0.1,False,False\nBengaluru,2024-06-10,31.4,15.0,4.8,False,False,,False,0.0,False,False\nBengaluru,2024-06-11,30.2,12.0,9.0,False,False,,False,0.0,False,False\nBengaluru,2024-06-12,34.4,11.8,7.0,False,False,,False,0.1,False,False\nBengaluru,2024-06-13,31.4,12.0,34.9,False,False,,False,0.0,False,False\nBengaluru,2024-06-14,33.9,14.6,27.7,False,False,,False,0.0,False,False\nBengaluru,2024-06-15,31.0,12.9,15.2,False,False,,False,0.0,False,False\nBengaluru,2024-06-16,32.9,12.9,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-06-17,28.9,12.8,8.9,False,False,,False,0.0,False,False\nBengaluru,2024-06-18,30.3,13.4,44.2,False,False,,False,0.1,False,False\nBengaluru,2024-06-19,29.5,12.3,22.8,False,False,,False,0.1,False,False\nBengaluru,2024-06-20,33.3,12.5,5.6,False,False,,False,0.1,False,False\nBengaluru,2024-06-21,32.3,12.1,0.1,False,False,,False,0.1,False,False\nBengaluru,2024-06-22,29.4,12.6,19.3,False,False,,False,0.0,False,False\nBengaluru,2024-06-23,29.2,10.9,6.1,False,False,,False,0.1,False,False\nBengaluru,2024-06-24,32.5,11.8,47.5,False,False,,False,0.1,False,False\nBengaluru,2024-06-25,32.4,11.2,20.6,False,False,,False,0.0,False,False\nBengaluru,2024-06-26,28.3,15.4,4.3,False,False,,False,0.1,False,False\nBengaluru,2024-06-27,33.1,14.0,1.5,False,False,,False,0.1,False,False\nBengaluru,2024-06-28,33.5,11.3,5.9,False,False,,False,0.0,False,False\nBengaluru,2024-06-29,32.3,12.5,16.4,False,False,,False,0.1,False,False\nBengaluru,2024-06-30,33.1,14.0,10.2,False,False,,False,0.0,False,False\nBengaluru,2024-07-01,25.4,9.7,3.7,False,False,,False,0.0,False,False\nBengaluru,2024-07-02,23.5,8.9,37.4,False,False,,False,0.0,False,False\nBengaluru,2024-07-03,25.4,10.0,21.9,False,False,,False,0.1,False,False\nBengaluru,2024-07-04,25.0,7.9,18.9,False,False,,False,0.1,False,False\nBengaluru,2024-07-05,24.9,10.3,18.0,False,False,,False,0.1,False,False\nBengaluru,2024-07-06,25.0,8.9,2.7,False,False,,False,0.0,False,False\nBengaluru,2024-07-07,22.0,9.7,7.9,False,False,,False,0.1,False,False\nBengaluru,2024-07-08,23.5,8.0,18.5,False,False,,False,0.1,False,False\nBengaluru,2024-07-09,23.0,9.0,30.1,False,False,,False,0.4,False,False\nBengaluru,2024-07-10,23.8,10.7,68.6,False,False,,False,0.3,False,False\nBengaluru,2024-07-11,23.6,9.1,14.0,False,False,,False,0.0,False,False\nBengaluru,2024-07-12,24.1,9.6,62.3,False,False,,False,0.0,False,False\nBengaluru,2024-07-13,26.5,8.8,21.4,False,False,,False,0.3,False,False\nBengaluru,2024-07-14,25.5,8.9,31.5,False,False,,False,0.2,False,False\nBengaluru,2024-07-15,23.4,9.2,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-07-16,23.7,11.8,49.4,False,False,,False,0.0,False,False\nBengaluru,2024-07-17,24.3,8.9,21.0,False,False,,False,0.1,False,False\nBengaluru,2024-07-18,24.0,10.6,16.1,False,False,,False,0.1,False,False\nBengaluru,2024-07-19,23.5,8.1,17.8,False,False,,False,0.1,False,False\nBengaluru,2024-07-20,20.7,12.3,8.6,False,False,,False,0.3,False,False\nBengaluru,2024-07-21,22.8,9.4,3.2,False,False,,False,0.0,False,False\nBengaluru,2024-07-22,25.1,8.8,4.6,False,False,,False,0.3,False,False\nBengaluru,2024-07-23,24.6,7.3,22.8,False,False,,False,0.0,False,False\nBengaluru,2024-07-24,22.7,8.3,29.5,False,False,,False,0.1,False,False\nBengaluru,2024-07-25,22.7,10.6,30.5,False,False,,False,0.1,False,False\nBengaluru,2024-07-26,23.1,8.9,2.8,False,False,,False,0.0,False,False\nBengaluru,2024-07-27,22.7,8.6,9.6,False,False,,False,0.0,False,False\nBengaluru,2024-07-28,24.3,10.2,10.5,False,False,,False,0.0,False,False\nBengaluru,2024-07-29,21.7,10.8,7.1,False,False,,False,0.0,False,False\nBengaluru,2024-07-30,22.3,8.0,18.7,False,False,,False,0.1,False,False\nBengaluru,2024-07-31,23.3,10.2,24.6,False,False,,False,0.1,False,False\nBengaluru,2024-08-01,22.0,6.3,36.3,False,False,,False,0.3,False,False\nBengaluru,2024-08-02,22.9,9.7,49.0,False,False,,False,0.1,False,False\nBengaluru,2024-08-03,21.7,11.5,8.7,False,False,,False,0.1,False,False\nBengaluru,2024-08-04,24.2,9.4,54.4,False,False,,False,0.0,False,False\nBengaluru,2024-08-05,24.5,9.0,17.8,False,False,,False,0.1,False,False\nBengaluru,2024-08-06,22.5,9.6,33.4,False,False,,False,0.1,False,False\nBengaluru,2024-08-07,22.8,10.6,15.8,False,False,,False,0.1,False,False\nBengaluru,2024-08-08,24.8,9.4,0.1,False,False,,False,0.0,False,False\nBengaluru,2024-08-09,22.0,8.8,26.9,False,False,,False,0.1,False,False\nBengaluru,2024-08-10,24.4,8.3,11.5,False,False,,False,0.2,False,False\nBengaluru,2024-08-11,23.8,9.2,28.1,False,False,,False,0.1,False,False\nBengaluru,2024-08-12,21.9,10.8,0.0,False,False,,False,0.1,False,False\nBengaluru,2024-08-13,24.5,10.1,34.6,False,False,,False,0.2,False,False\nBengaluru,2024-08-14,20.6,8.3,17.6,False,False,,False,0.1,False,False\nBengaluru,2024-08-15,20.9,9.8,17.7,False,False,,False,0.2,False,False\nBengaluru,2024-08-16,22.8,8.9,13.2,False,False,,False,0.0,False,False\nBengaluru,2024-08-17,23.2,8.8,1.9,False,False,,False,0.1,False,False\nBengaluru,2024-08-18,20.3,7.6,16.5,False,False,,False,0.1,False,False\nBengaluru,2024-08-19,21.4,8.4,48.4,False,False,,False,0.1,False,False\nBengaluru,2024-08-20,21.9,8.9,6.6,False,False,,False,0.1,False,False\nBengaluru,2024-08-21,24.8,9.9,3.5,False,False,,False,0.1,False,False\nBengaluru,2024-08-22,22.5,8.0,42.7,False,False,,False,0.0,False,False\nBengaluru,2024-08-23,24.3,8.1,3.2,False,False,,False,0.0,False,False\nBengaluru,2024-08-24,21.0,8.3,41.1,False,False,,False,0.0,False,False\nBengaluru,2024-08-25,20.2,10.1,6.3,False,False,,False,0.1,False,False\nBengaluru,2024-08-26,24.3,9.8,61.1,False,False,,False,0.1,False,False\nBengaluru,2024-08-27,19.8,8.2,0.5,False,False,,False,0.1,False,False\nBengaluru,2024-08-28,20.8,9.1,66.9,False,False,,False,0.0,False,False\nBengaluru,2024-08-29,22.9,8.2,12.9,False,False,,False,0.1,False,False\nBengaluru,2024-08-30,23.3,9.8,20.7,False,False,,False,0.0,False,False\nBengaluru,2024-08-31,22.8,9.3,6.7,False,False,,False,0.1,False,False\nBengaluru,2024-09-01,26.9,10.1,22.3,False,False,,False,0.0,False,False\nBengaluru,2024-09-02,26.3,8.7,0.6,False,False,,False,0.1,False,False\nBengaluru,2024-09-03,24.4,8.2,11.4,False,False,,False,0.1,False,False\nBengaluru,2024-09-04,22.9,10.1,0.0,False,False,,False,0.1,False,False\nBengaluru,2024-09-05,26.0,10.4,3.9,False,False,,False,0.1,False,False\nBengaluru,2024-09-06,24.1,8.6,18.1,False,False,,False,0.1,False,False\nBengaluru,2024-09-07,27.0,9.6,21.0,False,False,,False,0.3,False,False\nBengaluru,2024-09-08,24.5,11.4,16.2,False,False,,False,0.1,False,False\nBengaluru,2024-09-09,22.5,10.1,14.0,False,False,,False,0.3,False,False\nBengaluru,2024-09-10,23.1,9.9,26.9,False,False,,False,0.2,False,False\nBengaluru,2024-09-11,21.8,9.3,17.3,False,False,,False,0.0,False,False\nBengaluru,2024-09-12,23.9,11.4,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-09-13,23.4,11.3,28.8,False,False,,False,0.0,False,False\nBengaluru,2024-09-14,26.4,10.5,9.4,False,False,,False,0.1,False,False\nBengaluru,2024-09-15,26.4,10.7,4.3,False,False,,False,0.1,False,False\nBengaluru,2024-09-16,26.9,7.9,18.1,False,False,,False,0.0,False,False\nBengaluru,2024-09-17,25.0,6.2,0.0,False,False,,False,0.0,False,False\nBengaluru,2024-09-18,26.4,9.8,0.7,False,False,,False,0.1,False,False\nBengaluru,2024-09-19,25.1,8.7,0.1,False,False,,False,0.0,False,False\nBengaluru,2024-09-20,24.1,8.3,9.5,False,False,,False,0.0,False,False\nBengaluru,2024-09-21,22.1,10.2,5.5,False,False,,False,0.0,False,False\nBengaluru,2024-09-22,25.6,8.7,1.8,False,False,,False,0.1,False,False\nBengaluru,2024-09-23,22.7,9.9,4.4,False,False,,False,0.0,False,False\nBengaluru,2024-09-24,26.4,10.9,3.4,False,False,,False,0.0,False,False\nBengaluru,2024-09-25,23.9,8.7,12.5,False,False,,False,0.1,False,False\nBengaluru,2024-09-26,25.7,9.1,21.5,False,False,,False,0.1,False,False\nBengaluru,2024-09-27,26.6,10.9,10.3,False,False,Big Sale,False,0.0,False,True\nBengaluru,2024-09-28,22.3,12.4,2.4,False,False,Big Sale,False,0.0,False,True\nBengaluru,2024-09-29,24.8,10.0,5.4,False,False,Big Sale,False,0.1,False,True\nBengaluru,2024-09-30,24.8,10.9,4.4,False,False,Big Sale,False,0.1,False,True\nBengaluru,2024-10-01,24.3,8.7,11.6,False,False,Big Sale,False,0.1,False,True\nBengaluru,2024-10-02,23.3,9.4,0.0,False,False,Big Sale,False,0.0,False,True\nBengaluru,2024-10-03,24.0,10.7,4.4,False,False,Big Sale,False,0.0,False,True\nBengaluru,2024-10-04,22.1,10.6,0.0,False,False,Big Sale,False,0.1,False,True\nBengaluru,2024-10-05,20.4,11.2,1.7,False,False,Big Sale,False,0.1,False

In [119]:
df2= pd.read_csv("city_daily_context.csv")

#FINDING MISSING VALUES

In [114]:
df2.isnull().sum()

city                          0
date                          0
max_temp_c                    0
min_temp_c                    0
rainfall_mm                   0
heat_alert                    0
flood_disruption              0
festival_or_event          3172
is_public_holiday             0
grid_outage_hours             0
competitor_promo_active       0
ecommerce_sale_event          0
dtype: int64

In [115]:
df2.shape

(3282, 12)

In [116]:
df2.size

39384

In [117]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3282 entries, 0 to 3281
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   city                     3282 non-null   object
 1   date                     3282 non-null   object
 2   max_temp_c               3282 non-null   float64
 3   min_temp_c               3282 non-null   float64
 4   rainfall_mm              3282 non-null   float64
 5   heat_alert               3282 non-null   bool
 6   flood_disruption         3282 non-null   bool
 7   festival_or_event        110 non-null    object
 8   is_public_holiday        3282 non-null   bool
 9   grid_outage_hours        3282 non-null   float64
 10  competitor_promo_active  3282 non-null   bool
 11  ecommerce_sale_event     3282 non-null   bool
dtypes: bool(5), float64(4), object(3)
memory usage: 195.6+ KB

In [118]:
df2.duplicated().sum() # zero duplicates values

np.int64(0)

In [121]:
df2.dtypes

city                        object
date                        object
max_temp_c                 float64
min_temp_c                 float64
rainfall_mm                float64
heat_alert                    bool
flood_disruption              bool
festival_or_event           object
is_public_holiday             bool
grid_outage_hours          float64
competitor_promo_active       bool
ecommerce_sale_event          bool
dtype: object

#CLEANING PART OF THE DATA

In [122]:
df2['date'] = pd.to_datetime(df2['date'])

In [123]:
df2["festival_or_event"] = df2["festival_or_event"].fillna("No Event")

# RECHECKING THE VALUES AFTER CLEANING

In [124]:
df2.isnull().sum()

city                       0
date                       0
max_temp_c                 0
min_temp_c                 0
rainfall_mm                0
heat_alert                 0
flood_disruption           0
festival_or_event          0
is_public_holiday          0
grid_outage_hours          0
competitor_promo_active    0
ecommerce_sale_event       0
dtype: int64

In [125]:
print(df2["date"].dtype)

datetime64[ns]

# NEW DATASET

In [130]:
df3=pd.read_csv("station_hourly_status.csv")
df3

,station_id,hour_start,charged_2w_avg,charged_2w_min,charged_3w_min,packs_charging,packs_quarantined,chargers_online,ambient_temp_c,cabinet_temp_c,avg_charge_minutes,outage_minutes,grid_kwh,telemetry_status
0,STN-BLR-001,2024-01-01 00:00:00,6.29,6.0,4.0,1.0,0.0,18,8.2,13.5,92.6,0,1.86,ok
1,STN-BLR-001,2024-01-01 01:00:00,8.10,8.0,4.0,8.0,0.0,18,8.2,11.5,88.0,0,13.96,ok
2,STN-BLR-001,2024-01-01 02:00:00,10.56,8.0,4.0,5.0,0.0,18,8.2,12.9,80.2,0,8.27,ok
3,STN-BLR-001,2024-01-01 03:00:00,7.44,6.0,3.0,5.0,0.0,18,8.2,13.2,86.7,0,8.38,ok
4,STN-BLR-001,2024-01-01 04:00:00,9.18,7.0,3.0,3.0,0.0,18,8.2,14.0,83.9,0,4.28,ok
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1487707,STN-TST-02,2025-06-30 19:00:00,6.23,6.0,NaN,3.0,0.0,8,30.2,39.2,66.2,0,5.85,ok
1487708,STN-TST-02,2025-06-30 20:00:00,6.48,6.0,NaN,2.0,0.0,8,28.3,34.0,57.1,0,3.82,ok
1487709,STN-TST-02,2025-06-30 21:00:00,7.32,7.0,NaN,3.0,0.0,8,18.0,23.9,65.0,0,6.09,ok
1487710,STN-TST-02,2025-06-30 22:00:00,5.20,3.0,NaN,1.0,0.0,8,18.0,24.9,68.5,0,1.72,ok
1487711,STN-TST-02,2025-06-30 23:00:00,4.98,2.0,NaN,3.0,0.0,8,18.0,24.4,67.1,0,5.79,ok

# FINDING MISSING VALUES AND DUPLICATES VALUES

In [131]:
df3.isnull().sum()

station_id                 0
hour_start                 0
charged_2w_avg          9384
charged_2w_min          9384
charged_3w_min        821808
packs_charging          9384
packs_quarantined       9384
chargers_online            0
ambient_temp_c          9384
cabinet_temp_c          9384
avg_charge_minutes      9384
outage_minutes             0
grid_kwh                9384
telemetry_status           0
dtype: int64

In [141]:
df3.head()

,station_id,hour_start,charged_2w_avg,charged_2w_min,charged_3w_min,packs_charging,packs_quarantined,chargers_online,ambient_temp_c,cabinet_temp_c,avg_charge_minutes,outage_minutes,grid_kwh,telemetry_status
0,STN-BLR-001,2024-01-01 00:00:00,6.29,6.0,4.0,1.0,0.0,18,8.2,13.5,92.6,0,1.86,ok
1,STN-BLR-001,2024-01-01 01:00:00,8.10,8.0,4.0,8.0,0.0,18,8.2,11.5,88.0,0,13.96,ok
2,STN-BLR-001,2024-01-01 02:00:00,10.56,8.0,4.0,5.0,0.0,18,8.2,12.9,80.2,0,8.27,ok
3,STN-BLR-001,2024-01-01 03:00:00,7.44,6.0,3.0,5.0,0.0,18,8.2,13.2,86.7,0,8.38,ok
4,STN-BLR-001,2024-01-01 04:00:00,9.18,7.0,3.0,3.0,0.0,18,8.2,14.0,83.9,0,4.28,ok

In [140]:
df3.tail()

,station_id,hour_start,charged_2w_avg,charged_2w_min,charged_3w_min,packs_charging,packs_quarantined,chargers_online,ambient_temp_c,cabinet_temp_c,avg_charge_minutes,outage_minutes,grid_kwh,telemetry_status
1487707,STN-TST-02,2025-06-30 19:00:00,6.23,6.0,NaN,3.0,0.0,8,30.2,39.2,66.2,0,5.85,ok
1487708,STN-TST-02,2025-06-30 20:00:00,6.48,6.0,NaN,2.0,0.0,8,28.3,34.0,57.1,0,3.82,ok
1487709,STN-TST-02,2025-06-30 21:00:00,7.32,7.0,NaN,3.0,0.0,8,18.0,23.9,65.0,0,6.09,ok
1487710,STN-TST-02,2025-06-30 22:00:00,5.20,3.0,NaN,1.0,0.0,8,18.0,24.9,68.5,0,1.72,ok
1487711,STN-TST-02,2025-06-30 23:00:00,4.98,2.0,NaN,3.0,0.0,8,18.0,24.4,67.1,0,5.79,ok

In [142]:
df3.shape

(1487712, 14)

In [143]:
df3.size

20827968

In [145]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1487712 entries, 0 to 1487711
Data columns (total 14 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   station_id          1487712 non-null  object
 1   hour_start          1487712 non-null  object
 2   charged_2w_avg      1478328 non-null  float64
 3   charged_2w_min      1478328 non-null  float64
 4   charged_3w_min      665904 non-null   float64
 5   packs_charging      1478328 non-null  float64
 6   packs_quarantined   1478328 non-null  float64
 7   chargers_online     1487712 non-null  int64
 8   ambient_temp_c      1478328 non-null  float64
 9   cabinet_temp_c      1478328 non-null  float64
 10  avg_charge_minutes  1478328 non-null  float64
 11  outage_minutes      1487712 non-null  int64
 12  grid_kwh            1478328 non-null  float64
 13  telemetry_status    1487712 non-null  object
dtypes: float64(9), int64(2), object(3)
memory usage: 158.9+ MB

In [146]:
df3.duplicated().sum()

np.int64(0)

# CELANING PART OF DATA

In [159]:
df3["hour_start"] = pd.to_datetime(df3["hour_start"])
print(df3["hour_start"].dtype)

datetime64[ns]

In [158]:
df3 = df3.drop_duplicates(subset=["station_id", "hour_start"])
df3

,station_id,hour_start,charged_2w_avg,charged_2w_min,charged_3w_min,packs_charging,packs_quarantined,chargers_online,ambient_temp_c,cabinet_temp_c,avg_charge_minutes,outage_minutes,grid_kwh,telemetry_status,has_data
0,STN-BLR-001,2024-01-01 00:00:00,6.29,6.0,4.0,1.0,0.0,18,8.2,13.5,92.6,0,1.86,ok,True
1,STN-BLR-001,2024-01-01 01:00:00,8.10,8.0,4.0,8.0,0.0,18,8.2,11.5,88.0,0,13.96,ok,True
2,STN-BLR-001,2024-01-01 02:00:00,10.56,8.0,4.0,5.0,0.0,18,8.2,12.9,80.2,0,8.27,ok,True
3,STN-BLR-001,2024-01-01 03:00:00,7.44,6.0,3.0,5.0,0.0,18,8.2,13.2,86.7,0,8.38,ok,True
4,STN-BLR-001,2024-01-01 04:00:00,9.18,7.0,3.0,3.0,0.0,18,8.2,14.0,83.9,0,4.28,ok,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1487707,STN-TST-02,2025-06-30 19:00:00,6.23,6.0,NaN,3.0,0.0,8,30.2,39.2,66.2,0,5.85,ok,True
1487708,STN-TST-02,2025-06-30 20:00:00,6.48,6.0,NaN,2.0,0.0,8,28.3,34.0,57.1,0,3.82,ok,True
1487709,STN-TST-02,2025-06-30 21:00:00,7.32,7.0,NaN,3.0,0.0,8,18.0,23.9,65.0,0,6.09,ok,True
1487710,STN-TST-02,2025-06-30 22:00:00,5.20,3.0,NaN,1.0,0.0,8,18.0,24.9,68.5,0,1.72,ok,True
1487711,STN-TST-02,2025-06-30 23:00:00,4.98,2.0,NaN,3.0,0.0,8,18.0,24.4,67.1,0,5.79,ok,True

In [157]:
df3["has_data"] = df3["telemetry_status"] != "missing"    #telemetry_status = "missing" ka matlab hai sensor se data hi nahi aaya — is row ko delete nahi karna, bas flag laga do taaki pata chale ye row "real data" hai ya nahi:
df3["has_data"]

0          True
1          True
2          True
3          True
4          True
           ...
1487707    True
1487708    True
1487709    True
1487710    True
1487711    True
Name: has_data, Length: 1487712, dtype: bool

In [161]:
df3.isnull().sum()

station_id                 0
hour_start                 0
charged_2w_avg          9384
charged_2w_min          9384
charged_3w_min        821808
packs_charging          9384
packs_quarantined       9384
chargers_online            0
ambient_temp_c          9384
cabinet_temp_c          9384
avg_charge_minutes      9384
outage_minutes             0
grid_kwh                9384
telemetry_status           0
has_data                   0
dtype: int64